spring:
  application:
    name: identity
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: ${IDENTITY_DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${IDENTITY_DB_SCHEMA:identity}
management:
  endpoints:
    web:
      exposure:
        include: health,info
