spring:
  datasource:
    url: ${NODIFIED_DB_URL}
    username: ${NODIFIED_DB_USERNAME}
    password: ${NODIFIED_DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

server:
  port: ${SERVER_PORT:8081}
