spring:
  application:
    name: monitor
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: ${MONITOR_DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${MONITOR_DB_SCHEMA:monitor}
  flyway:
    enabled: ${MONITOR_FLYWAY_ENABLED:true}
    schemas: ${MONITOR_DB_SCHEMA:monitor}
    default-schema: ${MONITOR_DB_SCHEMA:monitor}
    create-schemas: true
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
