spring:
  datasource:
    url: ${NODIFIED_DB_URL:jdbc:postgresql://localhost:5432/nodified}
    username: ${NODIFIED_DB_USERNAME:nodified}
    password: ${NODIFIED_DB_PASSWORD:nodified}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8081}

server:
  port: ${SERVER_PORT:8082}
